---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name:  nginx-ingress-lb
  namespace: prod
  labels:
    k8s-app: nginx-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nginx-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: nginx-ingress-lb
        name: nginx-ingress-lb
    spec:
      containers:
      - image: nginx
        name: nginx-ingress-lb
        ports:
        - name: http
          containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-web
  namespace: prod
spec:
  selector:
    k8s-app: nginx-ingress-lb
  ports:
  - name: nginx-web-port
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-web-ui
  namespace: prod
spec:
  rules:
  - host: nginx.lab.local
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-web
          servicePort: nginx-web-port
